# Generated by Django 4.2.7 on 2025-08-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_avatar_user_bio_user_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("platform_admin", "Platform Admin"),
                    ("admin", "Admin"),
                    ("client", "Client"),
                    ("accountant", "Accountant/Staff"),
                ],
                default="client",
                max_length=20,
            ),
        ),
    ]
