# Generated by Django 4.2.7 on 2025-08-04 07:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(default="UniPay", max_length=200)),
                (
                    "company_email",
                    models.EmailField(default="info@unipay.com", max_length=254),
                ),
                (
                    "company_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("company_address", models.TextField(blank=True, null=True)),
                ("company_website", models.URLField(blank=True, null=True)),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                ("default_currency", models.CharField(default="KES", max_length=3)),
                (
                    "default_tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=16.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "default_discount_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("default_payment_terms", models.IntegerField(default=30)),
                (
                    "invoice_number_prefix",
                    models.CharField(default="INV", max_length=10),
                ),
                ("invoice_number_start", models.IntegerField(default=1000)),
                ("auto_increment_invoice_numbers", models.BooleanField(default=True)),
                (
                    "invoice_template",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("modern", "Modern"),
                            ("classic", "Classic"),
                            ("minimal", "Minimal"),
                        ],
                        default="default",
                        max_length=20,
                    ),
                ),
                ("primary_color", models.CharField(default="#2563eb", max_length=7)),
                ("secondary_color", models.CharField(default="#374151", max_length=7)),
                ("invoice_footer_text", models.TextField(blank=True, null=True)),
                ("default_terms_conditions", models.TextField(blank=True, null=True)),
                ("default_notes", models.TextField(blank=True, null=True)),
                (
                    "pdf_page_size",
                    models.CharField(
                        choices=[
                            ("A4", "A4"),
                            ("Letter", "Letter"),
                            ("Legal", "Legal"),
                        ],
                        default="A4",
                        max_length=10,
                    ),
                ),
                (
                    "pdf_orientation",
                    models.CharField(
                        choices=[("portrait", "Portrait"), ("landscape", "Landscape")],
                        default="portrait",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Settings",
                "verbose_name_plural": "Company Settings",
            },
        ),
        migrations.CreateModel(
            name="IntegrationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("smtp_host", models.CharField(blank=True, max_length=100, null=True)),
                ("smtp_port", models.IntegerField(default=587)),
                (
                    "smtp_username",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "smtp_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("smtp_use_tls", models.BooleanField(default=True)),
                ("smtp_use_ssl", models.BooleanField(default=False)),
                ("stripe_enabled", models.BooleanField(default=False)),
                (
                    "stripe_publishable_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_secret_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_webhook_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("twilio_enabled", models.BooleanField(default=False)),
                (
                    "twilio_account_sid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "twilio_auth_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "twilio_phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("exchange_rate_api_enabled", models.BooleanField(default=True)),
                (
                    "exchange_rate_api_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "exchange_rate_api_url",
                    models.URLField(default="https://open.er-api.com/v6/latest/"),
                ),
                ("exchange_rate_cache_duration", models.IntegerField(default=3600)),
                ("supported_currencies", models.JSONField(default=list)),
                ("default_currency", models.CharField(default="KES", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Integration Settings",
                "verbose_name_plural": "Integration Settings",
            },
        ),
        migrations.CreateModel(
            name="InvoiceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_item_description",
                    models.CharField(default="Service", max_length=200),
                ),
                ("default_item_quantity", models.IntegerField(default=1)),
                (
                    "default_item_unit_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("draft_color", models.CharField(default="#6b7280", max_length=7)),
                ("pending_color", models.CharField(default="#f59e0b", max_length=7)),
                ("paid_color", models.CharField(default="#10b981", max_length=7)),
                ("overdue_color", models.CharField(default="#ef4444", max_length=7)),
                ("send_reminder_on_due_date", models.BooleanField(default=True)),
                ("send_reminder_before_due", models.BooleanField(default=True)),
                ("reminder_days_before_due", models.IntegerField(default=3)),
                ("send_overdue_reminder", models.BooleanField(default=True)),
                ("overdue_reminder_frequency", models.IntegerField(default=7)),
                ("notify_on_invoice_created", models.BooleanField(default=True)),
                ("notify_on_invoice_paid", models.BooleanField(default=True)),
                ("notify_on_invoice_overdue", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Invoice Settings",
                "verbose_name_plural": "Invoice Settings",
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                        ],
                        default="light",
                        max_length=20,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                ("timezone", models.CharField(default="Africa/Nairobi", max_length=50)),
                ("email_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("push_notifications", models.BooleanField(default=True)),
                ("dashboard_currency", models.CharField(default="KES", max_length=3)),
                ("show_recent_invoices", models.BooleanField(default=True)),
                ("show_recent_payments", models.BooleanField(default=True)),
                ("show_charts", models.BooleanField(default=True)),
                (
                    "default_invoice_template",
                    models.CharField(default="default", max_length=20),
                ),
                ("auto_save_drafts", models.BooleanField(default=True)),
                ("show_tax_breakdown", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Settings",
                "verbose_name_plural": "User Settings",
            },
        ),
    ]
