# Generated by Django 4.2.7 on 2025-08-10 08:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exchange_rate_api_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("exchange_rate_cache_duration", models.IntegerField(default=3600)),
                ("supported_currencies", models.JSONField(default=list)),
                ("smtp_host", models.CharField(blank=True, max_length=100, null=True)),
                ("smtp_port", models.IntegerField(default=587)),
                (
                    "smtp_username",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "smtp_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("smtp_use_tls", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform Settings",
                "verbose_name_plural": "Platform Settings",
            },
        ),
        migrations.CreateModel(
            name="UserProfileSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "company_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "company_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("company_address", models.TextField(blank=True, null=True)),
                ("company_website", models.URLField(blank=True, null=True)),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                (
                    "header_custom_text",
                    models.TextField(
                        blank=True,
                        help_text="Custom text to display in invoice header",
                        null=True,
                    ),
                ),
                ("show_logo_in_header", models.BooleanField(default=True)),
                ("show_contact_in_header", models.BooleanField(default=True)),
                ("show_address_in_header", models.BooleanField(default=True)),
                ("default_currency", models.CharField(default="KES", max_length=3)),
                (
                    "default_tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=16.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("default_payment_terms", models.IntegerField(default=30)),
                (
                    "invoice_number_prefix",
                    models.CharField(default="INV", max_length=10),
                ),
                ("invoice_number_start", models.IntegerField(default=1000)),
                ("email_notifications", models.BooleanField(default=True)),
                ("invoice_reminders", models.BooleanField(default=True)),
                ("payment_confirmations", models.BooleanField(default=True)),
                ("overdue_alerts", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile Settings",
                "verbose_name_plural": "User Profile Settings",
            },
        ),
        migrations.DeleteModel(
            name="CompanySettings",
        ),
        migrations.DeleteModel(
            name="IntegrationSettings",
        ),
        migrations.DeleteModel(
            name="InvoiceSettings",
        ),
        migrations.DeleteModel(
            name="UserSettings",
        ),
    ]
