# Generated by Django 4.2.7 on 2025-09-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_platformsettings_userprofilesettings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="admin_email",
            field=models.EmailField(default="admin@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="api_rate_limit",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="backup_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="backup_frequency",
            field=models.CharField(default="daily", max_length=20),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="backup_retention",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="cache_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="cache_timeout",
            field=models.IntegerField(default=3600),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="cors_origins",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="database_optimization",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="debug_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="default_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="default_tax_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="file_upload_limit",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="from_email",
            field=models.EmailField(default="noreply@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="from_name",
            field=models.CharField(default="Invoice Platform", max_length=100),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="grace_period",
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="invoice_prefix",
            field=models.CharField(default="INV", max_length=10),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="invoice_reminders",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="invoice_start_number",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="language",
            field=models.CharField(default="en", max_length=10),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="late_fee_rate",
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=5),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="lockout_duration",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="log_level",
            field=models.CharField(default="INFO", max_length=10),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="login_attempts",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="maintenance_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="max_invoices_per_month",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="max_users_per_org",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="overdue_alerts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="password_min_length",
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="password_require_special",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="payment_confirmations",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="payment_terms",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="platform_domain",
            field=models.CharField(default="localhost:3000", max_length=200),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="platform_name",
            field=models.CharField(default="Invoice Platform", max_length=200),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="registration_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="require_email_verification",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="require_two_factor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="session_timeout",
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="stripe_publishable_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="stripe_secret_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="support_email",
            field=models.EmailField(default="support@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="timezone",
            field=models.CharField(default="UTC", max_length=50),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="webhook_secret",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
