# Generated by Django 4.2.7 on 2025-09-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_platformsettings_admin_email_and_more"),
    ]

    operations = []
