# Generated by Django 4.2.7 on 2025-09-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0004_auto_20250902_1655"),
    ]

    operations = []
