# Generated by Django 4.2.7 on 2025-08-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_organization_user_organization"),
        ("payments", "0002_plan_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="accounts.organization",
            ),
            preserve_default=False,
        ),
    ]
