# Generated by Django 4.2.7 on 2025-08-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_organization_user_organization"),
        ("payments", "0003_subscription_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="accounts.organization",
            ),
        ),
    ]
