# Generated by Django 4.2.7 on 2025-09-15 06:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_usersession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0004_alter_subscription_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformPaymentGateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("flutterwave", "Flutterwave"),
                            ("mpesa", "M-Pesa"),
                        ],
                        help_text="Payment gateway name",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "api_secret_key",
                    models.CharField(
                        help_text="Platform's API secret key for this gateway",
                        max_length=500,
                    ),
                ),
                (
                    "api_public_key",
                    models.CharField(
                        help_text="Platform's API public key for this gateway",
                        max_length=500,
                    ),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True,
                        help_text="Platform's webhook secret for this gateway",
                        max_length=500,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[("sandbox", "Sandbox"), ("live", "Live")],
                        default="sandbox",
                        help_text="Gateway environment",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this gateway is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform Payment Gateway",
                "verbose_name_plural": "Platform Payment Gateways",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="plan",
            options={},
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="current_period_start",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="owner",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="interval",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="limits",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="provider_price_id",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="cancel_at_period_end",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="current_period_end",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="provider_customer_id",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="provider_subscription_id",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="trial_end",
        ),
        migrations.AddField(
            model_name="payment",
            name="gateway_session_id",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="plan",
            name="billing_cycle",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="auto_renew",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="KES", max_length=3),
        ),
        migrations.AlterField(
            model_name="payment",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_intent_id",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("flutterwave", "Flutterwave"),
                    ("mpesa", "M-Pesa"),
                    ("manual", "Manual Entry"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="plan",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="plan",
            name="features",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="payments.plan"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="payment",
            table=None,
        ),
        migrations.AlterModelTable(
            name="plan",
            table=None,
        ),
        migrations.AlterModelTable(
            name="subscription",
            table=None,
        ),
        migrations.CreateModel(
            name="UserPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("bank_account", "Bank Account"),
                            ("mpesa", "M-Pesa"),
                            ("card", "Credit/Debit Card"),
                            ("paypal", "PayPal"),
                            ("other", "Other"),
                        ],
                        help_text="Type of payment method",
                        max_length=20,
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(blank=True, help_text="Bank name", max_length=100),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        blank=True, help_text="Account number", max_length=50
                    ),
                ),
                (
                    "bank_account_name",
                    models.CharField(
                        blank=True, help_text="Account holder name", max_length=100
                    ),
                ),
                (
                    "bank_swift_code",
                    models.CharField(
                        blank=True, help_text="SWIFT/BIC code", max_length=20
                    ),
                ),
                (
                    "bank_branch_code",
                    models.CharField(
                        blank=True, help_text="Branch code", max_length=20
                    ),
                ),
                (
                    "mpesa_phone_number",
                    models.CharField(
                        blank=True,
                        help_text="M-Pesa phone number",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in format 254XXXXXXXXX",
                                regex="^254\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "mpesa_account_name",
                    models.CharField(
                        blank=True, help_text="M-Pesa account name", max_length=100
                    ),
                ),
                (
                    "card_last_four",
                    models.CharField(
                        blank=True, help_text="Last 4 digits of card", max_length=4
                    ),
                ),
                (
                    "card_brand",
                    models.CharField(
                        blank=True,
                        help_text="Card brand (Visa, Mastercard, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "card_expiry",
                    models.CharField(
                        blank=True, help_text="Card expiry (MM/YYYY)", max_length=7
                    ),
                ),
                (
                    "payment_details",
                    models.TextField(
                        blank=True, help_text="Additional payment details"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary payment method for this user"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this payment method is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Payment Method",
                "verbose_name_plural": "User Payment Methods",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("card", "Credit/Debit Card"),
                            ("bank_account", "Bank Account"),
                            ("mpesa", "M-Pesa"),
                            ("paypal", "PayPal"),
                            ("other", "Other"),
                        ],
                        help_text="Type of payment method",
                        max_length=20,
                    ),
                ),
                (
                    "card_last_four",
                    models.CharField(
                        blank=True, help_text="Last 4 digits of card", max_length=4
                    ),
                ),
                (
                    "card_brand",
                    models.CharField(
                        blank=True,
                        help_text="Card brand (Visa, Mastercard, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "card_expiry",
                    models.CharField(
                        blank=True, help_text="Card expiry (MM/YYYY)", max_length=7
                    ),
                ),
                (
                    "card_holder_name",
                    models.CharField(
                        blank=True, help_text="Card holder name", max_length=100
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(blank=True, help_text="Bank name", max_length=100),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        blank=True, help_text="Account number", max_length=50
                    ),
                ),
                (
                    "bank_account_name",
                    models.CharField(
                        blank=True, help_text="Account holder name", max_length=100
                    ),
                ),
                (
                    "mpesa_phone_number",
                    models.CharField(
                        blank=True,
                        help_text="M-Pesa phone number",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in format 254XXXXXXXXX",
                                regex="^254\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "payment_details",
                    models.TextField(
                        blank=True, help_text="Additional payment details"
                    ),
                ),
                (
                    "is_recurring_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable recurring payments with this method",
                    ),
                ),
                (
                    "recurring_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        help_text="Recurring payment frequency",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this payment method is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="accounts.client",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Payment Method",
                "verbose_name_plural": "Client Payment Methods",
                "ordering": ["-created_at"],
            },
        ),
    ]
