# Generated by Django 4.2.7 on 2025-09-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_platformpaymentgateway_alter_payment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(
                blank=True, help_text="Actual date when payment was received", null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_notes",
            field=models.TextField(
                blank=True, help_text="Additional notes about the payment"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                help_text="Reference number for manual payments",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="clientpaymentmethod",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("unipay", "Unipay (M-Pesa)"),
                    ("flutterwave", "Flutterwave"),
                    ("bank_account", "Bank Account"),
                    ("other", "Other"),
                ],
                help_text="Type of payment method",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("unipay", "Unipay (M-Pesa)"),
                    ("flutterwave", "Flutterwave"),
                    ("manual", "Manual Entry"),
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("check", "Check"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="platformpaymentgateway",
            name="name",
            field=models.CharField(
                choices=[("unipay", "Unipay (M-Pesa)"), ("flutterwave", "Flutterwave")],
                help_text="Payment gateway name",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="userpaymentmethod",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("unipay", "Unipay (M-Pesa)"),
                    ("flutterwave", "Flutterwave"),
                    ("bank_account", "Bank Account"),
                    ("other", "Other"),
                ],
                help_text="Type of payment method",
                max_length=20,
            ),
        ),
    ]
