# Generated by Django 4.2.7 on 2025-08-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_alter_invoice_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="currency",
            field=models.CharField(
                choices=[
                    ("KES", "Kenyan Shilling (KES)"),
                    ("USD", "US Dollar (USD)"),
                    ("EUR", "Euro (EUR)"),
                    ("GBP", "British Pound (GBP)"),
                    ("NGN", "Nigerian Naira (NGN)"),
                    ("GHS", "Ghanaian Cedi (GHS)"),
                    ("ZAR", "South African Rand (ZAR)"),
                    ("UGX", "Ugandan Shilling (UGX)"),
                    ("TZS", "Tanzanian Shilling (TZS)"),
                ],
                default="KES",
                max_length=3,
            ),
        ),
    ]
